apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitas-storagemanager
  namespace: sitas
spec:
  selector:
    matchLabels:
      app: sitas-storagemanager
  template:
    metadata:
      labels:
        app: sitas-storagemanager
    spec:
      containers:
        - name: sitas-storagemanager
          image: oscarvicente/sitas-storagemanager-prod
          env:
            - name: MONGODB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sitas-storagemanager-secret
                  key: MONGODB_ENDPOINT
            - name: MONGODB_DATABASE
              value: sitas-prod
            - name: MINIO_INTERNAL_ENDPOINT
              value: http://oscarvx00.ddns.net:10000
            - name: MINIO_INTERNAL_USER
              valueFrom:
                secretKeyRef:
                  name: sitas-storagemanager-secret
                  key: MINIO_INTERNAL_USER
            - name: MINIO_INTERNAL_PASS
              valueFrom:
                secretKeyRef:
                  name: sitas-storagemanager-secret
                  key: MINIO_INTERNAL_PASS
            - name: MINIO_INTERNAL_BUCKET
              value: internal-storage-prod
            - name: RABBITMQ_ENDPOINT
              value: goose-01.rmq2.cloudamqp.com
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: sitas-storagemanager-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: sitas-storagemanager-secret
                  key: RABBITMQ_PASS
            - name: RABBITMQ_VHOST
              value: oaoesvtq
            - name: RABBITMQ_QUEUE_DOWNLOADCOMPLETED
              value: sitas-prod-queue-downloadcompleted
